package com.example.doug.checklistpresentlayer

enum class kAction {
    ADD_USER, CREATE_TASK, COMPLETE_TASK, DELETE_TASK, CHANGE_TASK_NAME,
    CHANGE_TASK_RECURRING, CHANGE_TASK_DEADLINE, REMOVE_TASK_DEADLINE,
    CHANGE_RECURRING_DAYS, CHANGE_RECURRING_TIME, TASK_RECURRED
}